### PR TITLE
Fixed Direct Printing URL (PrintNode)

### PR DESCRIPTION
**Pull request by shadow046**
Add StorageController and Route to web.php

Fixed URL in PrintReceiptJobs.php

### CODE REVIEW

**Comment by ormelflores** [comment]
@shadow046 File path is currently working. if you are using `FILESYSTEM_DISK=public` make sure to run `php artisan storage:link` then try to regenerate the receipt

**Comment by shadow046** [comment]
> @shadow046 File path is currently working. if you are using `FILESYSTEM_DISK=public` make sure to run `php artisan storage:link` then try to regenerate the receipt

i already run storage:link.. but its not working.. coz the url send to printnode is /storage/transaction/... its not the correct path. its always download failed..

image

**Comment by ormelflores** [comment]
@shadow046 Have you checked on the public folder, if it was already linked? I'm already using Storage::disk()->url() which will return something like this `http://localhost/storage/folder/filename.pdf`as per laravels documentation

**Comment by ormelflores** [comment]
Additionally, it's working fine on my end and it does print the receipt successfully

> @shadow046 Have you checked on the public folder, if it was already linked? I'm already using Storage::disk()->url() which will return something like this `http://localhost/storage/folder/filename.pdf`as per laravels documentation

**Comment by shadow046** [comment]
> Additionally, it's working fine on my end and it does print the receipt successfully
> 
> > @shadow046 Have you checked on the public folder, if it was already linked? I'm already using Storage::disk()->url() which will return something like this `http://localhost/storage/folder/filename.pdf`as per laravels documentation

yes.. and i use dd and i saw that the return is this only '/storage/folder/filename.pdf'

**Comment by shadow046** [comment]
anyway thanks.. this one works on me :)

**Pull request closed without merging**
